name: generate-events
language: Python
variables:
  - name: output
    inputType: OutputTopic
    description: Name of the output topic to write to.
    defaultValue: user-events
    required: false
dockerfile: dockerfile
runEntryPoint: main.py
defaultFile: main.py
