name: Streamlit Real-time MotherDuck
language: python
variables:
  - name: input
    inputType: InputTopic
    description: Name of the input topic to listen to.
    required: true
  - name: MOTHERDUCK_TOKEN
    inputType: Secret
    description: ''
    defaultValue: mdtoken
    required: false
  - name: MOTHERDUCK_DATABASE
    inputType: FreeText
    description: ''
    defaultValue: my_db
    required: false
dockerfile: dockerfile
runEntryPoint: main.py
defaultFile: streamlit_file.py
