name: Superlinked Server Sink
language: python
variables:
  - name: input
    inputType: InputTopic
    description: This is the input topic
    defaultValue: user-events
    required: true
  - name: superlinked_host
    inputType: FreeText
    description: Host address for the superlinked instance
    defaultValue: 34.121.121.12
    required: true
  - name: superlinked_port
    inputType: FreeText
    description: Port for the superlinked instance
    defaultValue: 8080
    required: true
dockerfile: dockerfile
runEntryPoint: main.py
defaultFile: main.py
