name: MotherDuck Write
language: python
variables:
  - name: input
    inputType: InputTopic
    description: Name of the input topic to listen to.
    defaultValue: transform
    required: false
  - name: MOTHERDUCK_TOKEN
    inputType: Secret
    description: ''
    defaultValue: ''
    required: false
  - name: MOTHERDUCK_DATABASE
    inputType: FreeText
    description: ''
    defaultValue: ''
    required: false
dockerfile: dockerfile
runEntryPoint: main.py
defaultFile: main.py
