name: Streamlit Recommendations Dash
language: python
variables:
  - name: superlinked_host
    inputType: FreeText
    description: ''
    defaultValue: 34.121.121.12
    required: false
  - name: superlinked_port
    inputType: FreeText
    description: ''
    defaultValue: 8080
    required: false
dockerfile: dockerfile
runEntryPoint: main.py
defaultFile: streamlit_file.py
