name: Flask Web Gateway
language: python
variables:
  - name: MOTHERDUCK_TOKEN
    inputType: Secret
    description: ''
    defaultValue: mdtoken
    required: false
dockerfile: build/dockerfile
runEntryPoint: main.py
defaultFile: main.py
